import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes, useLocation } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import AllocationRequestPage from '../pages/AllocationRequestPage';
import RecommendationResultPage from '../pages/RecommendationResultPage';
import { getAgent3Session } from '../auth/agent3Session';
import { getRecommendationById, submitAllocationRequest } from '../api/agent3Api';
import { MOCK_PROCESS_INSTANCE_ID, MOCK_REQUESTER_ID, MOCK_TASK_ID, MOCK_TENANT_ID, mockPersistedAllocationResponse, mockRecommendationSummary } from './fixtures/agent3Contracts';

vi.mock('../auth/agent3Session', () => ({ getAgent3Session: vi.fn() }));
vi.mock('../api/agent3Api', () => ({ submitAllocationRequest: vi.fn(), getRecommendationById: vi.fn(), getRecommendationByCorrelationId: vi.fn() }));
const fakeSession = { requesterId: MOCK_REQUESTER_ID, tenantId: MOCK_TENANT_ID, accessToken: 'clearly-fake-token-never-render' };

function StateProbe() { const location = useLocation(); return <pre data-testid="navigation-state">{JSON.stringify(location.state)}</pre>; }
function renderForm(state?: unknown, destination: React.ReactNode = <RecommendationResultPage />) {
  return render(<MemoryRouter initialEntries={[{ pathname: '/agent3/allocations/new', state }]}><Routes><Route path="/agent3/allocations/new" element={<AllocationRequestPage />} /><Route path="/agent3/recommendations/:recommendationId" element={destination} /></Routes></MemoryRouter>);
}
async function ready(state?: unknown, destination?: React.ReactNode) {
  renderForm(state, destination); await screen.findByRole('heading', { name: 'Create allocation request' }); return userEvent.setup();
}
function fillHuman() {
  fireEvent.change(screen.getAllByLabelText(/Task deadline \(required\)/)[0], { target: { value: '2026-01-01T12:00' } });
  fireEvent.change(screen.getByLabelText(/Estimated effort hours/), { target: { value: '0.8750' } });
  fireEvent.change(screen.getAllByLabelText(/Process stage \(required\)/)[0], { target: { value: 'Review' } });
}
function fillBudget() {
  fireEvent.change(screen.getByLabelText(/Required amount/), { target: { value: '9999999999999999.99' } });
  fireEvent.change(screen.getByLabelText(/Currency \(required\)/), { target: { value: 'credits' } });
  const deadlines = screen.getAllByLabelText(/Task deadline \(required\)/); fireEvent.change(deadlines[deadlines.length - 1], { target: { value: '2026-01-01T12:00' } });
  const stages = screen.getAllByLabelText(/Process stage \(required\)/); fireEvent.change(stages[stages.length - 1], { target: { value: 'Finance' } });
}

describe('AllocationRequestPage', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(getAgent3Session).mockResolvedValue(fakeSession); vi.mocked(submitAllocationRequest).mockResolvedValue(mockPersistedAllocationResponse); vi.mocked(getRecommendationById).mockResolvedValue(mockRecommendationSummary); });
  it('shows session loading', () => { vi.mocked(getAgent3Session).mockReturnValue(new Promise(() => undefined)); renderForm(); expect(screen.getByRole('status')).toHaveTextContent('Verifying authenticated session'); });
  it('renders the form after a valid session', async () => { await ready(); expect(screen.getByRole('button', { name: 'Submit allocation request' })).toBeInTheDocument(); });
  it('fails closed for a missing session', async () => { vi.mocked(getAgent3Session).mockRejectedValue(new Error('secret')); renderForm(); expect(await screen.findByRole('alert')).toHaveTextContent('Authentication required'); expect(screen.queryByRole('button', { name: /Submit/ })).not.toBeInTheDocument(); });
  it('never renders token or editable tenant/requester controls', async () => { await ready(); expect(document.body).not.toHaveTextContent(fakeSession.accessToken); expect(screen.queryByLabelText(/tenant id/i)).not.toBeInTheDocument(); expect(screen.queryByLabelText(/requester id/i)).not.toBeInTheDocument(); });
  it('starts in HUMAN mode without workload fields', async () => { await ready(); expect(screen.getByRole('radio', { name: 'Human' })).toBeChecked(); expect(screen.getByText('Human requirement')).toBeInTheDocument(); expect(screen.queryByText('Budget requirement')).not.toBeInTheDocument(); expect(screen.queryByLabelText(/workload/i)).not.toBeInTheDocument(); });
  it('switches to BUDGET mode without submitting', async () => { const user = await ready(); await user.click(screen.getByRole('radio', { name: 'Budget' })); expect(screen.getByText('Budget requirement')).toBeInTheDocument(); expect(screen.queryByText('Human requirement')).not.toBeInTheDocument(); expect(submitAllocationRequest).not.toHaveBeenCalled(); });
  it('shows both sections in mixed mode', async () => { const user = await ready(); await user.click(screen.getByRole('radio', { name: 'Human + Budget' })); expect(screen.getByText('Human requirement')).toBeInTheDocument(); expect(screen.getByText('Budget requirement')).toBeInTheDocument(); });
  it('preserves entered values across mode switches', async () => { const user = await ready(); await user.type(screen.getByLabelText(/Required roles/), 'Lead'); await user.click(screen.getByRole('radio', { name: 'Budget' })); await user.click(screen.getByRole('radio', { name: 'Human' })); expect(screen.getByLabelText(/Required roles/)).toHaveValue('Lead'); });
  it('submits an exact HUMAN-only payload', async () => { const user = await ready(undefined, <StateProbe />); await user.type(screen.getByLabelText(/Required roles/), 'Lead, QA, Lead'); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); await waitFor(() => expect(submitAllocationRequest).toHaveBeenCalled()); const request = vi.mocked(submitAllocationRequest).mock.calls[0][0]; expect(request.human_requirements).toMatchObject({ required_roles: ['Lead','QA'], requester_id: MOCK_REQUESTER_ID, estimated_effort_hours: '0.8750' }); expect(request.budget_requirements).toBeNull(); });
  it('submits an exact BUDGET-only payload without a symbol', async () => { const user = await ready(undefined, <StateProbe />); await user.click(screen.getByRole('radio', { name: 'Budget' })); fillBudget(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); await waitFor(() => expect(submitAllocationRequest).toHaveBeenCalled()); const request = vi.mocked(submitAllocationRequest).mock.calls[0][0]; expect(request.human_requirements).toBeNull(); expect(request.budget_requirements).toMatchObject({ required_amount: '9999999999999999.99', currency: 'credits', cost_centre: null, requester_id: MOCK_REQUESTER_ID }); expect(document.body).not.toHaveTextContent('$'); });
  it('submits both sections with the same requester in mixed mode', async () => { const user = await ready(undefined, <StateProbe />); await user.click(screen.getByRole('radio', { name: 'Human + Budget' })); fillHuman(); fillBudget(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); await waitFor(() => expect(submitAllocationRequest).toHaveBeenCalled()); const request = vi.mocked(submitAllocationRequest).mock.calls[0][0]; expect(request.human_requirements?.requester_id).toBe(MOCK_REQUESTER_ID); expect(request.budget_requirements?.requester_id).toBe(MOCK_REQUESTER_ID); });
  it('prevents the whole mixed submission when one section is invalid', async () => { const user = await ready(); await user.click(screen.getByRole('radio', { name: 'Human + Budget' })); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); expect(submitAllocationRequest).not.toHaveBeenCalled(); });
  it('shows field errors and focuses the error summary', async () => { const user = await ready(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); const alert = await screen.findByRole('alert'); await waitFor(() => expect(alert).toHaveFocus()); expect(screen.getAllByText('Enter a task deadline.')).toHaveLength(2); });
  it('uses application-supplied workflow IDs without using supplied identity fields', async () => { const user = await ready({ processInstanceId: MOCK_PROCESS_INSTANCE_ID, taskId: MOCK_TASK_ID, tenantId: '00000000-0000-0000-0000-000000000099', requesterId: '00000000-0000-0000-0000-000000000098' }, <StateProbe />); expect(screen.queryByText('Standalone demo mode')).not.toBeInTheDocument(); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); await waitFor(() => expect(submitAllocationRequest).toHaveBeenCalled()); const request = vi.mocked(submitAllocationRequest).mock.calls[0][0]; expect(request.metadata).toMatchObject({ process_instance_id: MOCK_PROCESS_INSTANCE_ID, task_id: MOCK_TASK_ID, tenant_id: MOCK_TENANT_ID, schema_version: '1.0.0', message_type: 'RESOURCE_ALLOCATION_REQUEST' }); expect(request.human_requirements?.requester_id).toBe(MOCK_REQUESTER_ID); expect(request.metadata.timestamp).toMatch(/Z$/); expect(document.body.textContent).not.toMatch(/trusted|verified workflow/i); });
  it('uses standalone demo mode for invalid supplied workflow identifiers', async () => { await ready({ processInstanceId: 'invalid', taskId: MOCK_TASK_ID }); expect(screen.getByText('Standalone demo mode')).toBeInTheDocument(); });
  it('labels demo fallback and preserves correlation after validation', async () => { const user = await ready(undefined, <StateProbe />); expect(screen.getByText('Standalone demo mode')).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); await waitFor(() => expect(submitAllocationRequest).toHaveBeenCalled()); expect(vi.mocked(submitAllocationRequest).mock.calls[0][0].metadata.correlation_id).toMatch(/^[0-9a-f-]{36}$/); });
  it('preserves correlation and demo workflow IDs across a retryable failure and manual retry', async () => { const user = await ready(undefined, <StateProbe />); vi.mocked(submitAllocationRequest).mockRejectedValueOnce({ kind: 'unavailable', retryable: true }).mockResolvedValueOnce(mockPersistedAllocationResponse); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); expect(await screen.findByText(/draft have been preserved/)).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); await waitFor(() => expect(submitAllocationRequest).toHaveBeenCalledTimes(2)); const first = vi.mocked(submitAllocationRequest).mock.calls[0][0].metadata; const second = vi.mocked(submitAllocationRequest).mock.calls[1][0].metadata; expect(second.correlation_id).toBe(first.correlation_id); expect(second.process_instance_id).toBe(first.process_instance_id); expect(second.task_id).toBe(first.task_id); });
  it('prevents double submission while pending', async () => { const user = await ready(); vi.mocked(submitAllocationRequest).mockReturnValue(new Promise(() => undefined)); fillHuman(); const button = screen.getByRole('button', { name: 'Submit allocation request' }); await user.dblClick(button); expect(submitAllocationRequest).toHaveBeenCalledTimes(1); expect(button).toBeDisabled(); });
  it('passes only the persisted response in navigation state', async () => { const user = await ready(undefined, <StateProbe />); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); const state = await screen.findByTestId('navigation-state'); expect(state).toHaveTextContent('persistedResponse'); expect(state).not.toHaveTextContent(fakeSession.accessToken); expect(state).not.toHaveTextContent('Authorization'); });
  it('renders a persisted pending result with copy success announcement', async () => { const user = await ready(); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); expect(await screen.findByText('Pending Human Approval')).toBeInTheDocument(); expect(screen.getByText(mockPersistedAllocationResponse.correlation_id)).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Copy correlation ID' })); expect(await navigator.clipboard.readText()).toBe(mockPersistedAllocationResponse.correlation_id); expect(screen.getByText('Correlation ID copied.')).toBeInTheDocument(); expect(screen.getByText('Yes (true)')).toBeInTheDocument(); });
  it('renders FAILED as technical failure and exposes no workflow actions', async () => { const failed = structuredClone(mockPersistedAllocationResponse); failed.recommendation_status = 'FAILED'; failed.recommendation.status = 'FAILED'; failed.recommendation.requires_human_approval = false; failed.recommendation.manual_intervention_required = true; vi.mocked(submitAllocationRequest).mockResolvedValue(failed); const user = await ready(); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); expect((await screen.findAllByText('Technical Failure')).length).toBeGreaterThan(0); expect(screen.queryByText(/Rejected/i)).not.toBeInTheDocument(); for (const name of ['Approve','Reject','Execute','Assign','Delete']) expect(screen.queryByRole('button', { name })).not.toBeInTheDocument(); });
  it('shows a safe 409 state with the preserved correlation', async () => { vi.mocked(submitAllocationRequest).mockRejectedValue({ kind: 'conflict', retryable: false }); const user = await ready(); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); expect(await screen.findByText(/may already exist/)).toBeInTheDocument(); expect(screen.getByText(/Correlation ID:/)).toBeInTheDocument(); });
  it('shows a safe 401 state', async () => { vi.mocked(submitAllocationRequest).mockRejectedValue({ kind: 'authentication', retryable: false, message: '<script>secret</script>' }); const user = await ready(); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); expect(await screen.findByText(/session has expired/)).toBeInTheDocument(); expect(document.body).not.toHaveTextContent('secret'); });
  it('shows a manual retry state for 503 without automatic retry', async () => { vi.mocked(submitAllocationRequest).mockRejectedValue({ kind: 'unavailable', retryable: true, message: 'postgresql://fake:password@host/db' }); const user = await ready(); fillHuman(); await user.click(screen.getByRole('button', { name: 'Submit allocation request' })); expect(await screen.findByText(/temporarily unavailable/)).toBeInTheDocument(); expect(submitAllocationRequest).toHaveBeenCalledTimes(1); expect(document.body).not.toHaveTextContent('password'); });
});

describe('RecommendationResultPage direct navigation', () => {
  it('does not call the API for an invalid direct route ID', async () => { render(<MemoryRouter initialEntries={['/agent3/recommendations/direct-id']}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Invalid recommendation ID')).toBeInTheDocument(); expect(getRecommendationById).not.toHaveBeenCalled(); });
  it('rejects malformed state without rendering raw HTML and loads summary', async () => { render(<MemoryRouter initialEntries={[{ pathname: `/agent3/recommendations/${mockPersistedAllocationResponse.recommendation_id}`, state: { persistedResponse: '<script>raw secret</script>' } }]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Summary view')).toBeInTheDocument(); expect(document.body).not.toHaveTextContent('raw secret'); });
  it('rejects state whose recommendation ID differs from the route and loads summary', async () => { const id = '00000000-0000-0000-0000-000000000099'; vi.mocked(getRecommendationById).mockResolvedValue({ ...mockRecommendationSummary, recommendation_id: id }); render(<MemoryRouter initialEntries={[{ pathname: `/agent3/recommendations/${id}`, state: { persistedResponse: mockPersistedAllocationResponse } }]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Summary view')).toBeInTheDocument(); expect(getRecommendationById).toHaveBeenCalledWith(id); });
  it('announces clipboard rejection safely without rendering the raw error', async () => { const user = userEvent.setup(); vi.spyOn(navigator.clipboard, 'writeText').mockRejectedValueOnce(new Error('<script>clipboard secret</script>')); render(<MemoryRouter initialEntries={[{ pathname: `/agent3/recommendations/${mockPersistedAllocationResponse.recommendation_id}`, state: { persistedResponse: mockPersistedAllocationResponse } }]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); await user.click(screen.getByRole('button', { name: 'Copy correlation ID' })); expect(await screen.findByText('Unable to copy the correlation ID. Select and copy it manually.')).toBeInTheDocument(); expect(document.body).not.toHaveTextContent('clipboard secret'); });
  it('announces unavailable clipboard support safely', async () => { const descriptor = Object.getOwnPropertyDescriptor(navigator, 'clipboard'); Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined }); try { render(<MemoryRouter initialEntries={[{ pathname: `/agent3/recommendations/${mockPersistedAllocationResponse.recommendation_id}`, state: { persistedResponse: mockPersistedAllocationResponse } }]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); fireEvent.click(screen.getByRole('button', { name: 'Copy correlation ID' })); expect(await screen.findByText('Unable to copy the correlation ID. Select and copy it manually.')).toBeInTheDocument(); } finally { if (descriptor) Object.defineProperty(navigator, 'clipboard', descriptor); } });
});
