import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import { FullRecommendation, SummaryRecommendation } from '../components/RecommendationPresentation';
import { Agent3StatusBadge } from '../components/Agent3StatusBadge';
import type { PersistedAllocationResponse, RecommendationStatus } from '../types/agent3Api';
import { mockPersistedAllocationResponse, mockRecommendationSummary } from './fixtures/agent3Contracts';

const detailed: PersistedAllocationResponse = {
  ...structuredClone(mockPersistedAllocationResponse), recommendation_status: 'GENERATED',
  recommendation: {
    ...structuredClone(mockPersistedAllocationResponse.recommendation), status: 'GENERATED', confidence: '0.8750', explanation: 'Line one\n<script>not markup</script>',
    human_requirement_result: { resource_type: 'HUMAN', budget_validation: null,
      eligible_candidates: [
        { resource_id: '00000000-0000-0000-0000-000000000011', resource_type: 'HUMAN', name: 'Candidate B', rank: 2, allocation_score: '0.7000', score_breakdown: { role_match: '0.71', skill_match: '0.72', availability_score: '0.73', workload_fit: '0.74', authority_match: '0.75', total_score: '0.7000' }, current_workload_percentage: '25.50', projected_workload_percentage: '45.75', available_from: '2026-01-01T12:00:00Z', available_until: null, evidence_refs: { source_id: 'https://host.invalid/secret' } },
        { resource_id: '00000000-0000-0000-0000-000000000012', resource_type: 'HUMAN', name: 'Candidate A', rank: 1, allocation_score: '0.9000', score_breakdown: { role_match: '0.91', skill_match: '0.92', availability_score: '0.93', workload_fit: '0.94', authority_match: '0.95', total_score: '0.9000' }, current_workload_percentage: '10.00', projected_workload_percentage: '30.00', available_from: '2026-01-01T12:00:00Z', available_until: '2026-12-31T12:00:00Z', evidence_refs: {} },
      ], excluded_resources: [{ resource_id: '00000000-0000-0000-0000-000000000013', resource_type: 'HUMAN', name: 'Candidate X', exclusion_reasons: [{ reason: 'ROLE_MISMATCH', description: 'Role mismatch first', evidence_reference: 'ev-1' }, { reason: 'UNAVAILABLE', description: 'Unavailable second', evidence_reference: null }] }] },
    budget_requirement_result: { resource_type: 'BUDGET', eligible_candidates: [], excluded_resources: [], budget_validation: { resource_id: '00000000-0000-0000-0000-000000000014', name: 'Budget Alpha', sufficient_balance: true, cost_centre_match: false, currency_match: true, validity_period_valid: false, within_authorization_limit: true, available_balance: '9999999999999999.99', required_amount: '12000.00', evidence_references: { record: 'postgresql://fake.invalid/db' } } },
    resource_gaps: [{ gap_type: 'FIRST_GAP', resource_type: 'HUMAN', gap_description: 'First gap', eligible_count: 1, excluded_count: 2 }, { gap_type: 'SECOND_GAP', resource_type: 'BUDGET', gap_description: 'Second gap', eligible_count: 0, excluded_count: 1 }],
    alternatives: [{ alternative_type: 'FIRST_ALT', description: 'First alternative', requires_approval: true, estimated_effort_hours: '8.50', cost_impact: '100.00' }, { alternative_type: 'SECOND_ALT', description: 'Second alternative', requires_approval: false, estimated_effort_hours: null, cost_impact: null }],
    limitations: ['<img src=x onerror=secret>', 'Second limitation'], requires_human_approval: true, manual_intervention_required: false,
  },
};

describe('full recommendation presentation', () => {
  it('preserves exact confidence', () => { render(<FullRecommendation response={detailed} />); expect(screen.getByText('0.8750')).toBeInTheDocument(); });
  it('preserves candidate order instead of reranking', () => { render(<FullRecommendation response={detailed} />); const rows = within(screen.getByRole('table')).getAllByRole('row'); expect(rows[1]).toHaveTextContent('Candidate B'); expect(rows[2]).toHaveTextContent('Candidate A'); });
  it.each(['0.7000','0.71','0.72','0.73','0.74','0.75'])('renders exact score %s without recomputation', (score) => { render(<FullRecommendation response={detailed} />); expect(screen.getByText(score)).toBeInTheDocument(); });
  it('labels workload values as percentages only', () => { render(<FullRecommendation response={detailed} />); expect(screen.getByText('25.50%')).toBeInTheDocument(); expect(screen.getByText('45.75%')).toBeInTheDocument(); expect(screen.queryByText('0.71%')).not.toBeInTheDocument(); });
  it('preserves exclusion reason order', () => { render(<FullRecommendation response={detailed} />); const list = screen.getByText('Candidate X').parentElement!; expect(list.textContent!.indexOf('Role mismatch first')).toBeLessThan(list.textContent!.indexOf('Unavailable second')); });
  it('renders all budget checks with pass/fail text', () => { render(<FullRecommendation response={detailed} />); expect(screen.getAllByText(/Pass:/)).toHaveLength(3); expect(screen.getAllByText(/Check failed:/)).toHaveLength(2); });
  it.each(['9999999999999999.99','12000.00'])('preserves exact budget Decimal %s', (value) => { render(<FullRecommendation response={detailed} />); expect(screen.getByText(value)).toBeInTheDocument(); });
  it('does not invent currency or symbols', () => { render(<FullRecommendation response={detailed} />); expect(document.body).not.toHaveTextContent('$'); expect(screen.queryByText(/USD|currency:/i)).not.toBeInTheDocument(); });
  it('distinguishes a failed budget check from technical failure', () => { render(<FullRecommendation response={detailed} />); expect(screen.getAllByText(/Check failed:/).length).toBeGreaterThan(0); expect(screen.queryByText('The recommendation could not be completed safely.')).not.toBeInTheDocument(); });
  it('preserves gap order', () => { render(<FullRecommendation response={detailed} />); expect(document.body.textContent!.indexOf('FIRST_GAP')).toBeLessThan(document.body.textContent!.indexOf('SECOND_GAP')); });
  it('preserves alternative order and provides no actions', () => { render(<FullRecommendation response={detailed} />); expect(document.body.textContent!.indexOf('FIRST_ALT')).toBeLessThan(document.body.textContent!.indexOf('SECOND_ALT')); expect(screen.queryByRole('button', { name: /FIRST_ALT|SECOND_ALT/ })).not.toBeInTheDocument(); });
  it('renders hostile explanation and limitations as escaped plain text', () => { render(<FullRecommendation response={detailed} />); expect(screen.getByText((_, element) => element?.tagName === 'P' && Boolean(element.textContent?.includes('<script>not markup</script>')))).toBeInTheDocument(); expect(screen.getByText('<img src=x onerror=secret>')).toBeInTheDocument(); expect(document.querySelector('script')).toBeNull(); expect(document.querySelector('img')).toBeNull(); });
  it('does not expose arbitrary evidence values or links', () => { render(<FullRecommendation response={detailed} />); expect(document.body).not.toHaveTextContent('https://host.invalid/secret'); expect(document.body).not.toHaveTextContent('postgresql://fake.invalid/db'); expect(screen.queryByRole('link', { name: /evidence/i })).not.toBeInTheDocument(); });
  it('contains its wide table for mobile overflow', () => { render(<FullRecommendation response={detailed} />); expect(screen.getByRole('region', { name: 'Ranked human candidates table' })).toHaveClass('overflow-x-auto'); });
  it('renders explicit empty states', () => { const empty = structuredClone(detailed); empty.recommendation.human_requirement_result = { resource_type: 'HUMAN', eligible_candidates: [], excluded_resources: [], budget_validation: null }; empty.recommendation.budget_requirement_result = null; render(<FullRecommendation response={empty} />); expect(screen.getByText('No eligible candidates were found.')).toBeInTheDocument(); expect(screen.getByText('No resources were excluded.')).toBeInTheDocument(); expect(screen.getByText('No BUDGET requirement was included.')).toBeInTheDocument(); });
  it('renders safe explanation empty state', () => { const empty = structuredClone(detailed); empty.recommendation.explanation = ''; render(<FullRecommendation response={empty} />); expect(screen.getByText('No explanation was provided.')).toBeInTheDocument(); });
});

describe('status and failure presentation', () => {
  it.each([['GENERATED','Generated'],['PENDING_HUMAN_APPROVAL','Pending Human Approval'],['SUPERSEDED','Superseded'],['FAILED','Technical Failure']] as [RecommendationStatus,string][])(
    'labels %s as %s with text', (status, label) => { render(<Agent3StatusBadge status={status} />); expect(screen.getByRole('status')).toHaveTextContent(label); });
  it('hides disallowed full details for FAILED', () => { const failed = structuredClone(detailed); failed.recommendation_status = 'FAILED'; failed.recommendation.status = 'FAILED'; failed.recommendation.confidence = null; failed.recommendation.error_code = 'SAFE_FAILURE'; failed.recommendation.retryable = false; failed.recommendation.requires_human_approval = false; failed.recommendation.manual_intervention_required = true; render(<FullRecommendation response={failed} />); expect(screen.getByText('SAFE_FAILURE')).toBeInTheDocument(); expect(screen.queryByText('Candidate B')).not.toBeInTheDocument(); expect(screen.queryByText('FIRST_GAP')).not.toBeInTheDocument(); expect(screen.queryByText('0.8750')).not.toBeInTheDocument(); expect(document.body).not.toHaveTextContent('Rejected'); });
  it('summary view never renders full sections', () => { render(<SummaryRecommendation summary={mockRecommendationSummary} />); expect(screen.getByText('Summary view')).toBeInTheDocument(); expect(screen.queryByText('Human allocation')).not.toBeInTheDocument(); expect(screen.queryByText('Budget validation')).not.toBeInTheDocument(); });
  it('does not claim unsupported AI provenance', () => { render(<FullRecommendation response={detailed} />); expect(document.body).not.toHaveTextContent(/AI-generated|model/i); });
  it('copy announces success', async () => { const user = userEvent.setup(); render(<SummaryRecommendation summary={mockRecommendationSummary} />); await user.click(screen.getByRole('button', { name: 'Copy correlation ID' })); expect(await screen.findByText('Correlation ID copied.')).toBeInTheDocument(); });
  it('copy announces failure without raw error', async () => { const user = userEvent.setup(); vi.spyOn(navigator.clipboard, 'writeText').mockRejectedValueOnce(new Error('secret')); render(<SummaryRecommendation summary={mockRecommendationSummary} />); await user.click(screen.getByRole('button', { name: 'Copy correlation ID' })); expect(await screen.findByText(/Unable to copy/)).toBeInTheDocument(); expect(document.body).not.toHaveTextContent('secret'); });
});
