import { act, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes, useNavigate } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { getRecommendationById } from '../api/agent3Api';
import RecommendationResultPage from '../pages/RecommendationResultPage';
import { MOCK_RECOMMENDATION_ID, mockPersistedAllocationResponse, mockRecommendationSummary } from './fixtures/agent3Contracts';

vi.mock('../api/agent3Api', () => ({ getRecommendationById: vi.fn() }));
const secondId = '00000000-0000-0000-0000-000000000099';
function Harness() { const navigate = useNavigate(); return <><button onClick={() => navigate(`/agent3/recommendations/${secondId}`)}>Next route</button><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></>; }
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((done) => { resolve = done; }); return { promise, resolve }; }

describe('RecommendationResultPage loading boundary', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(getRecommendationById).mockResolvedValue(mockRecommendationSummary); });
  it('renders validated POST state fully without GET', async () => { render(<MemoryRouter initialEntries={[{ pathname: `/agent3/recommendations/${MOCK_RECOMMENDATION_ID}`, state: { persistedResponse: mockPersistedAllocationResponse } }]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(screen.getByText('Human allocation')).toBeInTheDocument(); expect(screen.queryByText('Summary view')).not.toBeInTheDocument(); expect(getRecommendationById).not.toHaveBeenCalled(); });
  it('loads summary when state is missing', async () => { render(<MemoryRouter initialEntries={[`/agent3/recommendations/${MOCK_RECOMMENDATION_ID}`]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Summary view')).toBeInTheDocument(); expect(getRecommendationById).toHaveBeenCalledWith(MOCK_RECOMMENDATION_ID); });
  it('loads summary when state is malformed', async () => { render(<MemoryRouter initialEntries={[{ pathname: `/agent3/recommendations/${MOCK_RECOMMENDATION_ID}`, state: { persistedResponse: '<b>bad</b>' } }]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Summary view')).toBeInTheDocument(); });
  it('loads summary when route and state IDs differ', async () => { vi.mocked(getRecommendationById).mockResolvedValue({ ...mockRecommendationSummary, recommendation_id: secondId }); render(<MemoryRouter initialEntries={[{ pathname: `/agent3/recommendations/${secondId}`, state: { persistedResponse: mockPersistedAllocationResponse } }]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Summary view')).toBeInTheDocument(); expect(getRecommendationById).toHaveBeenCalledWith(secondId); });
  it('rejects a fetched summary whose ID differs from the route', async () => { render(<MemoryRouter initialEntries={[`/agent3/recommendations/${secondId}`]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('The returned recommendation did not match the requested identifier.')).toBeInTheDocument(); expect(screen.queryByText('Summary view')).not.toBeInTheDocument(); });
  it('rejects invalid route UUID without GET', async () => { render(<MemoryRouter initialEntries={['/agent3/recommendations/not-a-uuid']}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Invalid recommendation ID')).toBeInTheDocument(); expect(getRecommendationById).not.toHaveBeenCalled(); });
  it('prevents stale GET result replacing a newer route', async () => { const first = deferred<typeof mockRecommendationSummary>(); const second = deferred<typeof mockRecommendationSummary>(); vi.mocked(getRecommendationById).mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise); const user = userEvent.setup(); render(<MemoryRouter initialEntries={[`/agent3/recommendations/${MOCK_RECOMMENDATION_ID}`]}><Harness /></MemoryRouter>); await user.click(screen.getByRole('button', { name: 'Next route' })); await act(async () => second.resolve({ ...mockRecommendationSummary, recommendation_id: secondId, explanation: 'Newest result' })); expect(await screen.findByText('Newest result')).toBeInTheDocument(); await act(async () => first.resolve({ ...mockRecommendationSummary, explanation: 'Stale result' })); expect(screen.queryByText('Stale result')).not.toBeInTheDocument(); });
  it('does not update state after unmount', async () => { const pending = deferred<typeof mockRecommendationSummary>(); vi.mocked(getRecommendationById).mockReturnValue(pending.promise); const view = render(<MemoryRouter initialEntries={[`/agent3/recommendations/${MOCK_RECOMMENDATION_ID}`]}><Routes><Route path="/agent3/recommendations/:recommendationId" element={<RecommendationResultPage />} /></Routes></MemoryRouter>); view.unmount(); await act(async () => pending.resolve(mockRecommendationSummary)); expect(view.container).toBeEmptyDOMElement(); });
});
