import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { getRecommendationByCorrelationId, getRecommendationById } from '../api/agent3Api';
import RecommendationLookupPage from '../pages/RecommendationLookupPage';
import { MOCK_CORRELATION_ID, MOCK_RECOMMENDATION_ID, mockRecommendationSummary } from './fixtures/agent3Contracts';

vi.mock('../api/agent3Api', () => ({ getRecommendationById: vi.fn(), getRecommendationByCorrelationId: vi.fn() }));
const renderPage = () => render(<MemoryRouter><RecommendationLookupPage /></MemoryRouter>);
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((done) => { resolve = done; }); return { promise, resolve }; }

describe('RecommendationLookupPage', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(getRecommendationById).mockResolvedValue(mockRecommendationSummary); vi.mocked(getRecommendationByCorrelationId).mockResolvedValue(mockRecommendationSummary); });
  it('looks up a recommendation ID and renders summary only', async () => { const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); expect(await screen.findByText('Summary view')).toBeInTheDocument(); expect(getRecommendationById).toHaveBeenCalledWith(MOCK_RECOMMENDATION_ID); expect(screen.queryByText('Human allocation')).not.toBeInTheDocument(); });
  it('looks up a correlation ID', async () => { const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Correlation ID'), MOCK_CORRELATION_ID); await user.click(screen.getByRole('button', { name: 'Find by correlation' })); expect(await screen.findByText('Summary view')).toBeInTheDocument(); expect(getRecommendationByCorrelationId).toHaveBeenCalledWith(MOCK_CORRELATION_ID); });
  it.each([['Recommendation ID','Find recommendation'],['Correlation ID','Find by correlation']] as const)('blocks invalid %s locally', async (label, button) => { const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText(label), 'invalid'); await user.click(screen.getByRole('button', { name: button })); expect(screen.getByText('Enter a valid UUID.')).toBeInTheDocument(); expect(getRecommendationById).not.toHaveBeenCalled(); expect(getRecommendationByCorrelationId).not.toHaveBeenCalled(); });
  it('supports keyboard submission', async () => { const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), `${MOCK_RECOMMENDATION_ID}{Enter}`); await waitFor(() => expect(getRecommendationById).toHaveBeenCalledWith(MOCK_RECOMMENDATION_ID)); });
  it('shows accessible loading state', async () => { vi.mocked(getRecommendationById).mockReturnValue(new Promise(() => undefined)); const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); expect(screen.getByRole('status')).toHaveTextContent('Loading recommendation'); expect(screen.getByRole('button', { name: 'Find recommendation' })).toBeDisabled(); });
  it.each([
    ['authentication','Authentication required','Your session is unavailable or expired.'],
    ['authorization','Access unavailable','not authorized'],
    ['not_found','Recommendation unavailable','not found or is not available to this tenant'],
    ['conflict','Lookup conflict','recommendation conflict'],
    ['unexpected','Lookup failed','could not be retrieved safely'],
  ])('renders safe %s error', async (kind, title, message) => { vi.mocked(getRecommendationById).mockRejectedValue({ kind, retryable: false, message: '<script>password SQL postgresql://fake</script>' }); const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); expect(await screen.findByText(title)).toBeInTheDocument(); expect(screen.getByText(new RegExp(message))).toBeInTheDocument(); expect(document.body).not.toHaveTextContent('password SQL'); });
  it('uses identical tenant-safe 404 copy regardless of source detail', async () => { vi.mocked(getRecommendationById).mockRejectedValue({ kind: 'not_found', retryable: false, message: 'cross tenant owner exists' }); const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); expect(await screen.findByText('The recommendation was not found or is not available to this tenant.')).toBeInTheDocument(); expect(document.body).not.toHaveTextContent('owner exists'); });
  it('retries 503 with the same method and ID only when requested', async () => { vi.mocked(getRecommendationById).mockRejectedValueOnce({ kind: 'unavailable', retryable: true }).mockResolvedValueOnce(mockRecommendationSummary); const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); expect(await screen.findByRole('button', { name: 'Retry lookup' })).toBeInTheDocument(); expect(getRecommendationById).toHaveBeenCalledTimes(1); await user.click(screen.getByRole('button', { name: 'Retry lookup' })); expect(await screen.findByText('Summary view')).toBeInTheDocument(); expect(getRecommendationById).toHaveBeenNthCalledWith(2, MOCK_RECOMMENDATION_ID); });
  it('does not offer retry for non-retryable errors', async () => { vi.mocked(getRecommendationById).mockRejectedValue({ kind: 'not_found', retryable: false }); const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); await screen.findByText('Recommendation unavailable'); expect(screen.queryByRole('button', { name: 'Retry lookup' })).not.toBeInTheDocument(); });
  it('focuses the error state after lookup failure', async () => { vi.mocked(getRecommendationById).mockRejectedValue({ kind: 'unexpected', retryable: false }); const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); const alert = await screen.findByRole('alert'); await waitFor(() => expect(alert).toHaveFocus()); });
  it('ignores stale lookup results', async () => { const first = deferred<typeof mockRecommendationSummary>(); const second = deferred<typeof mockRecommendationSummary>(); vi.mocked(getRecommendationById).mockReturnValue(first.promise); vi.mocked(getRecommendationByCorrelationId).mockReturnValue(second.promise); renderPage(); fireEvent.change(screen.getByLabelText('Recommendation ID'), { target: { value: MOCK_RECOMMENDATION_ID } }); fireEvent.submit(screen.getByRole('button', { name: 'Find recommendation' }).closest('form')!); fireEvent.change(screen.getByLabelText('Correlation ID'), { target: { value: MOCK_CORRELATION_ID } }); fireEvent.submit(screen.getByRole('button', { name: 'Find by correlation' }).closest('form')!); await act(async () => second.resolve({ ...mockRecommendationSummary, explanation: 'Newest lookup' })); expect(await screen.findByText('Newest lookup')).toBeInTheDocument(); await act(async () => first.resolve({ ...mockRecommendationSummary, explanation: 'Stale lookup' })); expect(screen.queryByText('Stale lookup')).not.toBeInTheDocument(); });
  it('preserves exact summary confidence', async () => { vi.mocked(getRecommendationById).mockResolvedValue({ ...mockRecommendationSummary, confidence: '0.8750' }); const user = userEvent.setup(); renderPage(); await user.type(screen.getByLabelText('Recommendation ID'), MOCK_RECOMMENDATION_ID); await user.click(screen.getByRole('button', { name: 'Find recommendation' })); expect(await screen.findByText('0.8750')).toBeInTheDocument(); });
});
