"""
Agent 2 — LLM & Agent Schemas (Pydantic v2)

Defines all structured data contracts used by Agent 2 to communicate with:
- Google Gemini (structured outputs / function calling)
- Agent 4 (Orchestrator) and inter-agent messages
- Internal cognitive cycle components (Planner, Tool Guard, Diagnoser, Recovery, Optimizer)

Gemini Compatibility Rules:
- Fields use strict, clean types (str, int, float, bool, Literal, list, dict).
- Avoid Optional/Unions where standard defaults (" ", 0, 0.0, False, [], {}) can be used.
- Every model includes a docstring documenting who produces it and its operational role.
"""

from typing import Any, Dict, List, Literal
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# 1. AgentMessage
# ---------------------------------------------------------------------------

class AgentMessage(BaseModel):
    """
    Represents an inter-agent message exchanged between Agent 2 and other platform agents
    (Agent 4 Orchestrator, Agent 1 Document Intelligence, Agent 3 Resource Allocation).

    Produced by: Agent 2 messaging service or received from Agent 4.
    Operational role: Standardized wire format for asynchronous inter-agent protocol.
    """

    message_id: str = Field(..., description="Unique message identifier (UUID)")
    process_id: str = Field(..., description="Target process instance ID")
    trace_id: str = Field(default="", description="Distributed trace correlation ID")
    sender: str = Field(..., description="Identifier of the sending agent (e.g., agent_4)")
    receiver: str = Field(..., description="Identifier of the receiving agent (e.g., agent_2)")
    task_type: str = Field(..., description="Actionable task category or event type")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Task context, parameters, or result data")
    evidence_refs: List[str] = Field(default_factory=list, description="References to supporting receipts, document IDs, or logs")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Agent confidence score (0.0 to 1.0)")
    status: Literal[
        "AUTHORIZED",
        "EXECUTION_RESULT",
        "COMPLETED",
        "FAILED",
        "PENDING",
        "REJECTED",
        "CANCELLED",
    ] = Field(default="PENDING", description="Message lifecycle or authorization status")


# ---------------------------------------------------------------------------
# 2. ExecutionPlan
# ---------------------------------------------------------------------------

class ExecutionPlan(BaseModel):
    """
    Represents a multi-step execution plan generated by Gemini for a specific task.

    Produced by: Google Gemini LLM during the PLAN phase of the cognitive cycle.
    Operational role: Describes the proposed step sequence, required tools, risk profile, and human intervention need.
    """

    task_id: str = Field(..., description="ID of the task to be executed")
    objective: str = Field(..., description="Clear statement of what execution aims to achieve")
    steps: List[str] = Field(..., description="Sequential step-by-step description of the execution path")
    selected_tools: List[str] = Field(..., description="List of tool names required for execution")
    reasoning_summary: str = Field(..., description="Summary of Gemini's reasoning behind this plan")
    risk_level: Literal["LOW", "MEDIUM", "HIGH"] = Field(..., description="Assessed execution risk level")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Gemini's self-assessed plan confidence score")
    fallback_strategy: str = Field(default="", description="Plan to execute if primary tool calls fail")
    requires_human: bool = Field(default=False, description="Flag indicating if plan requires human approval before ACT")


# ---------------------------------------------------------------------------
# 3. AgentDecision
# ---------------------------------------------------------------------------

class AgentDecision(BaseModel):
    """
    Represents a structured decision made by Gemini for a single cognitive cycle step.

    Produced by: Google Gemini LLM during the REASON / PLAN phase.
    Operational role: Governs whether Agent 2 will EXECUTE a tool call, ESCALATE to human, or REJECT an unauthorized task.
    """

    decision: Literal["EXECUTE", "ESCALATE", "REJECT"] = Field(..., description="Core decision outcome")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Decision confidence score (0.0 to 1.0)")
    selected_tool: str = Field(default="", description="Name of the tool selected for execution (if EXECUTE)")
    reason: str = Field(..., description="Detailed rationale for the decision")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Structured parameters for the tool call")
    risk_level: Literal["LOW", "MEDIUM", "HIGH"] = Field(default="MEDIUM", description="Risk level of taking this action")
    fallback_strategy: str = Field(default="", description="Fallback action if the primary tool call fails")
    requires_human: bool = Field(default=False, description="Whether human approval is required prior to execution")


# ---------------------------------------------------------------------------
# 4. ToolCall & ToolResult
# ---------------------------------------------------------------------------

class ToolCallContract(BaseModel):
    """
    Represents a single tool call invocation proposed by Gemini or prepared by the Execution Engine.

    Produced by: Gemini LLM (as function call output) or Execution Engine.
    Operational role: Encapsulates tool identity and parameters prior to Tool Guard validation.
    """

    name: str = Field(..., description="Allowed tool identifier (e.g., send_role_email, create_po_draft)")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="JSON argument payload for tool execution")


class ToolResultContract(BaseModel):
    """
    Represents the output and execution metrics of a completed tool call.

    Produced by: Tool Guard / Tool Execution Subsystem.
    Operational role: Recorded into tool_calls DB table and passed to OBSERVE phase of cognitive cycle.
    """

    name: str = Field(..., description="Name of the executed tool")
    result: Dict[str, Any] = Field(default_factory=dict, description="Return payload from tool execution")
    status: Literal["SUCCESS", "FAILED", "BLOCKED", "TIMEOUT"] = Field(..., description="Execution status")
    latency_ms: int = Field(default=0, ge=0, description="Tool execution duration in milliseconds")
    error_message: str = Field(default="", description="Detailed error text if execution failed or was blocked")


# ---------------------------------------------------------------------------
# 5. FailureDiagnosis
# ---------------------------------------------------------------------------

class FailureDiagnosis(BaseModel):
    """
    Represents root cause diagnosis and failure classification performed when an action fails.

    Produced by: Gemini LLM or Failure Diagnosis Engine during DIAGNOSE phase.
    Operational role: Categorizes errors to select appropriate recovery strategies (retry, fallback, escalate).
    """

    failure_type: Literal[
        "TEMPORARY",
        "PERMANENT",
        "AUTHORIZATION",
        "VALIDATION",
        "DATA",
        "DUPLICATE",
        "TIMEOUT",
        "RATE_LIMIT",
        "UNKNOWN",
    ] = Field(..., description="Taxonomy classification of the failure")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of the diagnosis")
    reasoning: str = Field(..., description="Root cause analysis explanation")
    recommended_action: str = Field(..., description="Action recommendation (e.g. exponential backoff, escalate to manager)")


# ---------------------------------------------------------------------------
# 6. RecoveryDecision
# ---------------------------------------------------------------------------

class RecoveryDecision(BaseModel):
    """
    Represents the recovery strategy selected to address an identified execution failure.

    Produced by: Gemini LLM or Recovery Subsystem during RECOVER phase.
    Operational role: Directs whether to retry, wait, alter strategy, or escalate to human supervisor.
    """

    retry: bool = Field(..., description="Whether to attempt a retry of the failed action")
    delay_seconds: int = Field(default=0, ge=0, description="Delay before executing retry attempt")
    alternative_strategy: str = Field(default="", description="Alternative approach or fallback tool if primary failed")
    escalate: bool = Field(default=False, description="Whether to escalate to Agent 4 / human supervisor")
    reasoning: str = Field(default="", description="Explanation of why this recovery decision was chosen")


# ---------------------------------------------------------------------------
# 7. ExecutionReceipt
# ---------------------------------------------------------------------------

class ExecutionReceipt(BaseModel):
    """
    Represents an immutable, idempotent proof-of-execution record for external tool actions.

    Produced by: Agent 2 Tool Execution Engine upon completion of any external tool call.
    Operational role: Persisted to execution_receipts DB table; checked to enforce idempotency rule #3.
    """

    id: str = Field(..., description="Receipt unique ID")
    process_id: str = Field(..., description="Process instance ID")
    task_id: str = Field(..., description="Task ID")
    agent_id: str = Field(..., description="Agent identifier (agent_2)")
    tool_name: str = Field(..., description="Name of executed tool")
    action: str = Field(..., description="Action performed")
    attempt_number: int = Field(default=1, ge=1, description="Attempt number for this action")
    idempotency_key: str = Field(..., description="Deterministic key: {process_id}-{task_id}-{action}")
    started_at: str = Field(..., description="Execution start timestamp (ISO-8601)")
    completed_at: str = Field(default="", description="Execution completion timestamp (ISO-8601)")
    status: Literal["RUNNING", "SUCCESS", "FAILED", "BLOCKED", "SKIPPED"] = Field(..., description="Receipt status")
    result: Dict[str, Any] = Field(default_factory=dict, description="Result payload")
    error_type: str = Field(default="", description="Error category if failed")
    error_message: str = Field(default="", description="Detailed error message")
    latency_ms: int = Field(default=0, ge=0, description="Execution duration in milliseconds")


# ---------------------------------------------------------------------------
# 8. KPIResult
# ---------------------------------------------------------------------------

class KPIResult(BaseModel):
    """
    Represents aggregated key performance indicators for a process type over a specified time window.

    Produced by: Analytics Subsystem during LEARN FROM EXECUTION DATA phase.
    Operational role: Feeds into process mining and bottleneck analysis to generate optimization proposals.
    """

    process_type: str = Field(..., description="Category of process analyzed (e.g. procurement)")
    time_window_start: str = Field(..., description="ISO-8601 start of analytics time window")
    time_window_end: str = Field(..., description="ISO-8601 end of analytics time window")
    avg_cycle_time_hours: float = Field(default=0.0, ge=0.0, description="Average end-to-end process duration in hours")
    avg_task_duration_hours: float = Field(default=0.0, ge=0.0, description="Average individual task duration in hours")
    completion_rate: float = Field(default=0.0, ge=0.0, le=1.0, description="Process completion percentage (0.0 to 1.0)")
    sla_compliance_rate: float = Field(default=0.0, ge=0.0, le=1.0, description="Percentage of tasks completed within SLA")
    failure_rate: float = Field(default=0.0, ge=0.0, le=1.0, description="Task execution failure rate (0.0 to 1.0)")
    throughput: int = Field(default=0, ge=0, description="Total completed process instances in window")
    bottleneck_task: str = Field(default="", description="Identifier of the task with highest average delay")
    kpi_data: Dict[str, Any] = Field(default_factory=dict, description="Raw aggregated metrics payload")


# ---------------------------------------------------------------------------
# 9. SLAAnalysis
# ---------------------------------------------------------------------------

class SLAAnalysis(BaseModel):
    """
    Represents SLA compliance tracking and predictive breach analysis for an active task.

    Produced by: Analytics / SLA Tracking engine.
    Operational role: Evaluates breach risk and triggers proactive escalation or reminders before breach occurs.
    """

    predicted_breach_probability: float = Field(..., ge=0.0, le=1.0, description="Predicted breach likelihood (0.0 to 1.0)")
    elapsed_hours: float = Field(..., ge=0.0, description="Hours elapsed since task assignment")
    sla_hours: float = Field(..., ge=0.0, description="Total target SLA hours for task")
    historical_average_hours: float = Field(..., ge=0.0, description="Historical average duration for this task type")
    is_breached: bool = Field(default=False, description="Whether SLA target is currently breached")
    recommended_action: str = Field(default="", description="Proactive mitigation recommendation")


# ---------------------------------------------------------------------------
# 10. OptimizationRecommendationSchema
# ---------------------------------------------------------------------------

class OptimizationRecommendationSchema(BaseModel):
    """
    Represents an evidence-based process optimization proposal.

    Produced by: Optimization Engine / Gemini during OPTIMIZE & RECOMMEND phases.
    Operational role: Persisted into optimization_recommendations table; default status is PENDING_APPROVAL.
    Rule #5 invariant: Requires human approval via Agent 4 before becoming APPROVED.
    """

    id: str = Field(default="", description="Unique recommendation ID (UUID)")
    process_id: str = Field(..., description="Target process instance or process definition ID")
    recommendation_type: str = Field(..., description="Optimization type (e.g. BOTTLENECK_REDUCTION, AUTOMATION_CANDIDATE)")
    problem: str = Field(..., description="Description of the identified inefficiency or bottleneck")
    root_cause: str = Field(..., description="Root cause analysis based on process mining data")
    evidence: Dict[str, Any] = Field(default_factory=dict, description="Supporting KPI data, logs, and trace evidence")
    baseline_metric: float = Field(default=0.0, description="Current baseline metric value (e.g. 48.0 hours)")
    predicted_metric: float = Field(default=0.0, description="Projected metric value after optimization (e.g. 12.0 hours)")
    improvement_percent: float = Field(default=0.0, description="Expected percentage improvement")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Statistical confidence score")
    risk: Literal["LOW", "MEDIUM", "HIGH"] = Field(default="MEDIUM", description="Implementation risk assessment")
    requires_human_approval: bool = Field(
        default=True,
        description="Non-Negotiable Rule #5: ALWAYS True — Agent 2 never self-approves optimization proposals",
    )
    status: Literal["PENDING_APPROVAL", "APPROVED", "REJECTED", "IMPLEMENTED"] = Field(
        default="PENDING_APPROVAL",
        description="Non-Negotiable Rule #5: ALWAYS starts as PENDING_APPROVAL",
    )
    created_at: str = Field(default="", description="ISO-8601 creation timestamp")
    approved_by: str = Field(default="", description="User ID of human who approved recommendation")
    approved_at: str = Field(default="", description="ISO-8601 approval timestamp")
