import { forwardRef, useState } from 'react';
import type { AllocationRecommendation, BudgetValidationResult, PersistedAllocationResponse, RecommendationSummary, RequirementResult } from '../types/agent3Api';
import { formatTimestampToLocal } from '../utils/timestamps';
import { Agent3StatusBadge } from './Agent3StatusBadge';

const card = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm';
const focusButton = 'rounded border border-indigo-600 px-3 py-1 text-sm font-medium text-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2';

function CopyCorrelation({ value }: { value: string }) {
  const [status, setStatus] = useState('');
  async function copy() { try { if (!navigator.clipboard?.writeText) throw new Error(); await navigator.clipboard.writeText(value); setStatus('Correlation ID copied.'); } catch { setStatus('Unable to copy the correlation ID. Select and copy it manually.'); } }
  return <><button type="button" onClick={copy} className={focusButton}>Copy correlation ID</button><p aria-live="polite" className="mt-2 text-sm text-slate-600">{status}</p></>;
}

function Header({ recommendationId, correlationId, status, persistedAt, confidence, approval, intervention, persisted }: { recommendationId: string; correlationId: string; status: RecommendationSummary['status']; persistedAt: string; confidence: string | null; approval: boolean; intervention: boolean; persisted: boolean }) {
  return <section className={card}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wide text-indigo-600">Agent 3 recommendation</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Recommendation result</h1></div><Agent3StatusBadge status={status} /></div>
    <dl className="mt-6 grid gap-5 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Recommendation ID</dt><dd className="break-all font-mono text-sm">{recommendationId}</dd></div><div><dt className="text-sm text-slate-500">Correlation ID</dt><dd><span className="mb-2 block break-all font-mono text-sm">{correlationId}</span><CopyCorrelation value={correlationId} /></dd></div><div><dt className="text-sm text-slate-500">Persisted</dt><dd>{persisted ? 'Yes (true)' : 'Summary record'}</dd></div><div><dt className="text-sm text-slate-500">Persisted at</dt><dd>{formatTimestampToLocal(persistedAt)}</dd></div><div><dt className="text-sm text-slate-500">Confidence</dt><dd>{confidence ?? 'Not provided'}</dd></div><div><dt className="text-sm text-slate-500">Human approval required</dt><dd>{approval ? 'Yes' : 'No'}</dd></div><div><dt className="text-sm text-slate-500">Manual intervention required</dt><dd>{intervention ? 'Yes' : 'No'}</dd></div></dl>
  </section>;
}

function Explanation({ value }: { value: string }) { return <section className="rounded-xl border border-violet-200 bg-violet-50 p-5"><h2 className="text-xl font-semibold text-slate-900">Explanation</h2><p className="mt-3 whitespace-pre-wrap text-slate-700">{value.trim() || 'No explanation was provided.'}</p></section>; }

function TechnicalFailure({ errorCode, retryable }: { errorCode: string | null; retryable: boolean | null }) { return <section role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5"><h2 className="text-xl font-semibold text-red-800">Technical Failure</h2><p className="mt-2 text-red-800">The recommendation could not be completed safely. Manual intervention is required.</p><dl className="mt-3 grid gap-2 sm:grid-cols-2"><div><dt className="text-sm text-red-700">Error code</dt><dd className="font-mono">{errorCode ?? 'UNSPECIFIED_FAILURE'}</dd></div><div><dt className="text-sm text-red-700">Retryable</dt><dd>{retryable ? 'Yes' : 'No'}</dd></div></dl></section>; }

function EvidenceCount({ value }: { value: Record<string, unknown> }) { const count = Object.keys(value).length; return <span className="text-sm text-slate-500">{count ? `${count} evidence reference${count === 1 ? '' : 's'} recorded` : 'No evidence references'}</span>; }

function HumanResult({ result }: { result: RequirementResult | null }) {
  if (!result) return <section className={card}><h2 className="text-xl font-semibold">Human allocation</h2><p className="mt-2 text-slate-500">No HUMAN requirement was included.</p></section>;
  return <section className={card}><h2 className="text-xl font-semibold">Human allocation</h2>{result.eligible_candidates.length ? <div role="region" aria-label="Ranked human candidates table" tabIndex={0} className="mt-4 overflow-x-auto focus:outline-none focus:ring-2 focus:ring-indigo-500"><table className="min-w-[1050px] text-left text-sm"><caption className="sr-only">Ranked human candidates in backend-provided order</caption><thead className="border-b border-slate-200 text-slate-600"><tr>{['Rank','Candidate','Allocation score','Role match','Skill match','Availability','Workload fit','Authority match','Current workload','Projected workload','Evidence'].map((heading) => <th key={heading} scope="col" className="p-2">{heading}</th>)}</tr></thead><tbody>{result.eligible_candidates.map((candidate) => <tr key={candidate.resource_id} className="border-b border-slate-100"><td className="p-2">{candidate.rank}</td><td className="p-2"><span className="font-medium">{candidate.name}</span><span className="block break-all font-mono text-xs text-slate-500">{candidate.resource_id}</span></td><td className="p-2">{candidate.allocation_score}</td><td className="p-2">{candidate.score_breakdown.role_match}</td><td className="p-2">{candidate.score_breakdown.skill_match}</td><td className="p-2">{candidate.score_breakdown.availability_score}</td><td className="p-2">{candidate.score_breakdown.workload_fit}</td><td className="p-2">{candidate.score_breakdown.authority_match}</td><td className="p-2">{candidate.current_workload_percentage}%</td><td className="p-2">{candidate.projected_workload_percentage}%</td><td className="p-2"><EvidenceCount value={candidate.evidence_refs} /></td></tr>)}</tbody></table></div> : <p className="mt-3 text-slate-500">No eligible candidates were found.</p>}
    <h3 className="mt-6 text-lg font-semibold">Excluded resources</h3>{result.excluded_resources.length ? <ul className="mt-3 space-y-3">{result.excluded_resources.map((resource) => <li key={resource.resource_id} className="rounded-lg bg-slate-50 p-3"><p className="font-medium">{resource.name}</p><p className="break-all font-mono text-xs text-slate-500">{resource.resource_id}</p><ol className="mt-2 list-decimal space-y-1 pl-5">{resource.exclusion_reasons.map((reason, index) => <li key={`${reason.reason}-${index}`}><span className="font-medium">{reason.reason}:</span> {reason.description}{reason.evidence_reference && <span className="block text-sm text-slate-500">Evidence reference: {reason.evidence_reference}</span>}</li>)}</ol></li>)}</ul> : <p className="mt-2 text-slate-500">No resources were excluded.</p>}</section>;
}

function Check({ label, value }: { label: string; value: boolean }) { return <li className={value ? 'text-emerald-700' : 'text-red-700'}><span className="font-semibold">{value ? 'Pass' : 'Check failed'}:</span> {label}</li>; }
function BudgetPanel({ value }: { value: BudgetValidationResult }) { return <div className="mt-4 rounded-lg bg-slate-50 p-4"><h3 className="font-semibold">{value.name}</h3><p className="break-all font-mono text-xs text-slate-500">{value.resource_id}</p><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Available balance</dt><dd>{value.available_balance}</dd></div><div><dt className="text-sm text-slate-500">Required amount</dt><dd>{value.required_amount}</dd></div></dl><ul className="mt-4 grid gap-2 sm:grid-cols-2"><Check label="Sufficient balance" value={value.sufficient_balance} /><Check label="Cost-centre match" value={value.cost_centre_match} /><Check label="Currency match" value={value.currency_match} /><Check label="Validity period valid" value={value.validity_period_valid} /><Check label="Within authorization limit" value={value.within_authorization_limit} /></ul><p className="mt-3"><EvidenceCount value={value.evidence_references} /></p></div>; }
function BudgetResult({ result }: { result: RequirementResult | null }) { return <section className={card}><h2 className="text-xl font-semibold">Budget validation</h2>{!result ? <p className="mt-2 text-slate-500">No BUDGET requirement was included.</p> : result.budget_validation ? <BudgetPanel value={result.budget_validation} /> : <p className="mt-2 text-slate-500">No budget validation result was provided.</p>}</section>; }

function Lists({ recommendation }: { recommendation: AllocationRecommendation }) { return <><section className={card}><h2 className="text-xl font-semibold">Resource gaps</h2>{recommendation.resource_gaps.length ? <ol className="mt-3 space-y-3">{recommendation.resource_gaps.map((gap, index) => <li key={`${gap.gap_type}-${index}`}><h3 className="font-medium">{gap.gap_type} — {gap.resource_type}</h3><p>{gap.gap_description}</p><p className="text-sm text-slate-500">Eligible: {gap.eligible_count}; excluded: {gap.excluded_count}</p></li>)}</ol> : <p className="mt-2 text-slate-500">No resource gaps were reported.</p>}</section><section className={card}><h2 className="text-xl font-semibold">Alternatives for human consideration</h2>{recommendation.alternatives.length ? <ol className="mt-3 space-y-3">{recommendation.alternatives.map((alternative, index) => <li key={`${alternative.alternative_type}-${index}`}><h3 className="font-medium">{alternative.alternative_type}</h3><p>{alternative.description}</p><p className="text-sm text-slate-500">Requires approval: {alternative.requires_approval ? 'Yes' : 'No'}; estimated effort: {alternative.estimated_effort_hours ?? 'Not provided'}; cost impact: {alternative.cost_impact ?? 'Not provided'}</p></li>)}</ol> : <p className="mt-2 text-slate-500">No alternatives were reported.</p>}</section><section className={card}><h2 className="text-xl font-semibold">Limitations</h2>{recommendation.limitations.length ? <ul className="mt-3 list-disc space-y-1 pl-5">{recommendation.limitations.map((limitation, index) => <li key={index}>{limitation}</li>)}</ul> : <p className="mt-2 text-slate-500">No limitations were reported.</p>}</section></>; }

export function FullRecommendation({ response }: { response: PersistedAllocationResponse }) { const recommendation = response.recommendation; return <div className="space-y-6"><Header recommendationId={response.recommendation_id} correlationId={response.correlation_id} status={response.recommendation_status} persistedAt={response.persisted_at} confidence={recommendation.status === 'FAILED' ? null : recommendation.confidence} approval={recommendation.requires_human_approval} intervention={recommendation.manual_intervention_required} persisted />{recommendation.status === 'FAILED' ? <TechnicalFailure errorCode={recommendation.error_code} retryable={recommendation.retryable} /> : <><Explanation value={recommendation.explanation} /><HumanResult result={recommendation.human_requirement_result} /><BudgetResult result={recommendation.budget_requirement_result} /><Lists recommendation={recommendation} /></>}</div>; }

export function SummaryRecommendation({ summary }: { summary: RecommendationSummary }) { return <div className="space-y-6"><p className="inline-flex rounded-full bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">Summary view</p><Header recommendationId={summary.recommendation_id} correlationId={summary.correlation_id} status={summary.status} persistedAt={summary.persisted_at} confidence={summary.status === 'FAILED' ? null : summary.confidence} approval={summary.requires_human_approval} intervention={summary.manual_intervention_required} persisted={false} />{summary.status === 'FAILED' ? <TechnicalFailure errorCode={summary.error_code} retryable={summary.retryable} /> : <Explanation value={summary.explanation} />}<p className="rounded-lg bg-blue-50 p-4 text-blue-800">Detailed candidate and budget evidence is available only in the immediate persisted POST result until a backend full-detail read endpoint exists.</p></div>; }

export function RecommendationLoadingState() { return <section role="status" aria-busy="true" className={card}><h1 className="text-xl font-semibold">Loading recommendation</h1><p className="mt-2 text-slate-500">Retrieving the tenant-scoped recommendation summary…</p></section>; }
export const RecommendationErrorState = forwardRef<HTMLElement, { title: string; message: string; retry?: () => void }>(({ title, message, retry }, ref) => <section ref={ref} role="alert" tabIndex={-1} className="rounded-xl border border-red-200 bg-white p-5 focus:outline-none focus:ring-2 focus:ring-red-500"><h1 className="text-xl font-semibold text-red-800">{title}</h1><p className="mt-2 text-slate-700">{message}</p>{retry && <button type="button" onClick={retry} className={`mt-4 ${focusButton}`}>Retry lookup</button>}</section>);
RecommendationErrorState.displayName = 'RecommendationErrorState';
